CREATE TABLE Workout(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Date] VARCHAR(50) NOT NULL,
     WorkoutType VARCHAR(100) NOT NULL,
    Distance VARCHAR(100) NOT NULL,
    Remarks VARCHAR(300) NOT NULL
)