CREATE TABLE WorkoutType(
    Code VARCHAR(2) NOT NULL PRIMARY KEY,
    [Type] VARCHAR(100) NOT NULL
)
ALTER TABLE Workout ALTER COLUMN WorkoutType VARCHAR(2);
ALTER TABLE Workout ADD FOREIGN KEY (WorkoutType) REFERENCES WorkoutType(Code);